<template>
  <div>
    <v-layout wrap>
      <v-flex
        v-for="(theme, index) in themes"
        :key="theme.name"
        xs4
        class="text-center mb-3"
        :class="{ 'pr-3': (index + 1) % 3 !== 0 }"
      >
        <v-btn
          block
          class="mr-3 text-none no-text-transform"
          :class="{ shadow: selectedTheme === index }"
          :style="`background-color: ${theme.value.vuetify.themes.dark.secondary};
        color: ${theme.value.vuetify.themes.dark.primary};`"
          @click.stop="changeTheme(theme)"
        >
          <span style="white-space: normal">
            {{ theme.name }}
          </span>
        </v-btn>
      </v-flex>
    </v-layout>
  </div>
</template>

<script>
import { mdiRestore } from '@mdi/js'
import _ from 'lodash'
import Vue from 'vue'

export default {
  data: () => ({
    mdiRestore,
    // TODO put themes in JSON files and import here
    themes: [
      {
        name: 'Ventic',
        value: {
          state: {
            mainBackgroundImg: 'https://wallpaperaccess.com/full/1281664.jpg',
            backgroundImg: 'https://wallpaperaccess.com/full/1281664.jpg',
            backImg: true,
            backgroundBlur: 20,
            backTintOpacity: 0.6,
            tintColor: '#222222FF',
            panelOpacity: 'B3',
            menuOpacity: 'CC',
            selectedMediaBackground: true,
          },
          vuetify: {
            dark: true,
            themes: {
              dark: {
                primary: '#FF5555',
                secondary: '#292929',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#640000',
                primary2: '#810000',
                primary3: '#9F0013',
                primary4: '#BF0927',
                primary5: '#DF363E',
                primary6: '#FF726D',
                primary7: '#FF8F87',
                primary8: '#FFACA1',
                primary9: '#FFC9BC',
                primary10: '#FFE6D8',
                secondary1: '#000000',
                secondary2: '#000000',
                secondary3: '#000000',
                secondary4: '#000000',
                secondary5: '#151515',
                secondary6: '#3F3F3F',
                secondary7: '#565656',
                secondary8: '#6E6E6E',
                secondary9: '#888888',
                secondary10: '#A2A2A2',
                text: '#FFFFFF',
                text1: '#E2E2E2',
                text2: '#C6C6C6',
                text3: '#ABABAB',
                text4: '#919191',
                text5: '#777777',
                base: '#1E1E1E',
              },
              light: {
                primary: '#FF5555',
                secondary: '#292929',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#FFE6D8',
                primary2: '#FFC9BC',
                primary3: '#FFACA1',
                primary4: '#FF8F87',
                primary5: '#FF726D',
                primary6: '#DF363E',
                primary7: '#BF0927',
                primary8: '#9F0013',
                primary9: '#810000',
                primary10: '#640000',
                secondary1: '#A2A2A2',
                secondary2: '#888888',
                secondary3: '#6E6E6E',
                secondary4: '#565656',
                secondary5: '#3F3F3F',
                secondary6: '#151515',
                secondary7: '#000000',
                secondary8: '#000000',
                secondary9: '#000000',
                secondary10: '#000000',
                text: '#FFFFFF',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
          },
        },
      },
      {
        name: 'Razer',
        value: {
          state: {
            mainBackgroundImg: 'https://getwallpapers.com/wallpaper/full/8/9/d/9202.jpg',
            backgroundImg: 'https://getwallpapers.com/wallpaper/full/8/9/d/9202.jpg',
            backImg: true,
            backgroundBlur: 20,
            backTintOpacity: 0.6,
            tintColor: '#000000FF',
            panelOpacity: 'B3',
            menuOpacity: 'CC',
            selectedMediaBackground: false,
          },
          vuetify: {
            themes: {
              dark: {
                primary: '#66B933',
                secondary: '#000000',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#003800',
                primary2: '#005000',
                primary3: '#006900',
                primary4: '#2A8300',
                primary5: '#499E12',
                primary6: '#82D54F',
                primary7: '#9FF26A',
                primary8: '#BCFF85',
                primary9: '#D9FFA0',
                primary10: '#F7FFBD',
                secondary1: '#000000',
                secondary2: '#000000',
                secondary3: '#000000',
                secondary4: '#000000',
                secondary5: '#000000',
                secondary6: '#1B1B1B',
                secondary7: '#303030',
                secondary8: '#474747',
                secondary9: '#5E5E5E',
                secondary10: '#777777',
                text: '#FFFFFF',
                text1: '#E2E2E2',
                text2: '#C6C6C6',
                text3: '#ABABAB',
                text4: '#919191',
                text5: '#777777',
                base: '#1E1E1E',
              },
              light: {
                primary: '#66B933',
                secondary: '#000000',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#F7FFBD',
                primary2: '#D9FFA0',
                primary3: '#BCFF85',
                primary4: '#9FF26A',
                primary5: '#82D54F',
                primary6: '#499E12',
                primary7: '#2A8300',
                primary8: '#006900',
                primary9: '#005000',
                primary10: '#003800',
                secondary1: '#777777',
                secondary2: '#5E5E5E',
                secondary3: '#474747',
                secondary4: '#303030',
                secondary5: '#1B1B1B',
                secondary6: '#000000',
                secondary7: '#000000',
                secondary8: '#000000',
                secondary9: '#000000',
                secondary10: '#000000',
                text: '#FFFFFF',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
            dark: true,
          },
        },
      },
      {
        name: 'Frozen',
        value: {
          state: {
            mainBackgroundImg: 'https://wallpaperaccess.com/full/1253703.jpg',
            backgroundImg: 'https://wallpaperaccess.com/full/1253703.jpg',
            backImg: true,
            backgroundBlur: 20,
            backTintOpacity: 0.4,
            tintColor: '#C9C9C9FF',
            panelOpacity: 'CC',
            menuOpacity: 'E6',
            selectedMediaBackground: false,
          },
          vuetify: {
            themes: {
              dark: {
                primary: '#0013FF',
                secondary: '#A2E2FF',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#000073',
                primary2: '#00008D',
                primary3: '#0000A8',
                primary4: '#0000C4',
                primary5: '#0000E1',
                primary6: '#5033FF',
                primary7: '#794FFF',
                primary8: '#9C6AFF',
                primary9: '#BF85FF',
                primary10: '#E0A0FF',
                secondary1: '#0B5E77',
                secondary2: '#327690',
                secondary3: '#4F90AB',
                secondary4: '#6AABC6',
                secondary5: '#86C6E2',
                secondary6: '#BEFFFF',
                secondary7: '#DBFFFF',
                secondary8: '#F9FFFF',
                secondary9: '#FFFFFF',
                secondary10: '#FFFFFF',
                text: '#000000',
                text1: '#000000',
                text2: '#000000',
                text3: '#000000',
                text4: '#000000',
                text5: '#000000',
                base: '#1E1E1E',
              },
              light: {
                primary: '#0013FF',
                secondary: '#A2E2FF',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#E0A0FF',
                primary2: '#BF85FF',
                primary3: '#9C6AFF',
                primary4: '#794FFF',
                primary5: '#5033FF',
                primary6: '#0000E1',
                primary7: '#0000C4',
                primary8: '#0000A8',
                primary9: '#00008D',
                primary10: '#000073',
                secondary1: '#FFFFFF',
                secondary2: '#FFFFFF',
                secondary3: '#F9FFFF',
                secondary4: '#DBFFFF',
                secondary5: '#BEFFFF',
                secondary6: '#86C6E2',
                secondary7: '#6AABC6',
                secondary8: '#4F90AB',
                secondary9: '#327690',
                secondary10: '#0B5E77',
                text: '#000000',
                text1: '#1B1B1B',
                text2: '#303030',
                text3: '#474747',
                text4: '#5E5E5E',
                text5: '#777777',
                base: '#1E1E1E',
              },
            },
            dark: false,
          },
        },
      },
      {
        name: 'Serika dark',
        value: {
          vuetify: {
            themes: {
              dark: {
                primary: '#E2B714',
                secondary: '#323437',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#553B00',
                primary2: '#6D5200',
                primary3: '#886A00',
                primary4: '#A68300',
                primary5: '#C49C00',
                primary6: '#FFD23A',
                primary7: '#FFEF58',
                primary8: '#FFFF74',
                primary9: '#FFFF91',
                primary10: '#FFFFAD',
                secondary1: '#000000',
                secondary2: '#000000',
                secondary3: '#000000',
                secondary4: '#03060B',
                secondary5: '#1D1F22',
                secondary6: '#484B4E',
                secondary7: '#606266',
                secondary8: '#797B7F',
                secondary9: '#939599',
                secondary10: '#ADB0B3',
                text: '#E2E2E2',
                text1: '#C6C6C6',
                text2: '#ABABAB',
                text3: '#909090',
                text4: '#777777',
                text5: '#5E5E5E',
                base: '#1E1E1E',
              },
              light: {
                primary: '#E2B714',
                secondary: '#323437',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#FFFFAD',
                primary2: '#FFFF91',
                primary3: '#FFFF74',
                primary4: '#FFEF58',
                primary5: '#FFD23A',
                primary6: '#C49C00',
                primary7: '#A68300',
                primary8: '#886A00',
                primary9: '#6D5200',
                primary10: '#553B00',
                secondary1: '#ADB0B3',
                secondary2: '#939599',
                secondary3: '#797B7F',
                secondary4: '#606266',
                secondary5: '#484B4E',
                secondary6: '#1D1F22',
                secondary7: '#03060B',
                secondary8: '#000000',
                secondary9: '#000000',
                secondary10: '#000000',
                text: '#E2E2E2',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
            dark: true,
          },
          state: {
            mainBackgroundImg: '',
            backgroundImg: '',
            backImg: false,
            backgroundBlur: 20,
            backTintOpacity: 0.6,
            selectedMediaBackground: false,
            tintColor: '#222222FF',
            panelOpacity: 'FF',
            menuOpacity: 'FF',
          },
        },
      },
      {
        name: 'Ukraine',
        value: {
          vuetify: {
            themes: {
              dark: {
                primary: '#FFD700',
                secondary: '#0057B7',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#6B5600',
                primary2: '#866E00',
                primary3: '#A38700',
                primary4: '#C1A100',
                primary5: '#E0BC00',
                primary6: '#FFF338',
                primary7: '#FFFF59',
                primary8: '#FFFF77',
                primary9: '#FFFF94',
                primary10: '#FFFFB2',
                secondary1: '#000038',
                secondary2: '#00004F',
                secondary3: '#001967',
                secondary4: '#002B81',
                secondary5: '#00409C',
                secondary6: '#3B6FD3',
                secondary7: '#5D88F0',
                secondary8: '#7CA2FF',
                secondary9: '#9ABDFF',
                secondary10: '#B8D9FF',
                text: '#FFFFFF',
                text1: '#E2E2E2',
                text2: '#C6C6C6',
                text3: '#ABABAB',
                text4: '#919191',
                text5: '#777777',
                base: '#1E1E1E',
              },
              light: {
                primary: '#FFD700',
                secondary: '#0057B7',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#FFFFB2',
                primary2: '#FFFF94',
                primary3: '#FFFF77',
                primary4: '#FFFF59',
                primary5: '#FFF338',
                primary6: '#E0BC00',
                primary7: '#C1A100',
                primary8: '#A38700',
                primary9: '#866E00',
                primary10: '#6B5600',
                secondary1: '#B8D9FF',
                secondary2: '#9ABDFF',
                secondary3: '#7CA2FF',
                secondary4: '#5D88F0',
                secondary5: '#3B6FD3',
                secondary6: '#00409C',
                secondary7: '#002B81',
                secondary8: '#001967',
                secondary9: '#00004F',
                secondary10: '#000038',
                text: '#FFFFFF',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
            dark: true,
          },
          state: {
            mainBackgroundImg: 'https://wallpaperaccess.com/full/184085.jpg',
            backgroundImg: 'https://wallpaperaccess.com/full/184085.jpg',
            backImg: true,
            backgroundBlur: 20,
            backTintOpacity: 0.6,
            selectedMediaBackground: false,
            tintColor: '#000E33FF',
            panelOpacity: 'B3',
            menuOpacity: 'CC',
          },
        },
      },
      {
        name: 'Neon',
        value: {
          vuetify: {
            themes: {
              dark: {
                primary: '#F524FC',
                secondary: '#25146F',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#5E0071',
                primary2: '#7C008C',
                primary3: '#9A00A7',
                primary4: '#B800C2',
                primary5: '#D600DF',
                primary6: '#FF4FFF',
                primary7: '#FF71FF',
                primary8: '#FF91FF',
                primary9: '#FFB0FF',
                primary10: '#FFCFFF',
                secondary1: '#000000',
                secondary2: '#000019',
                secondary3: '#00002A',
                secondary4: '#00003F',
                secondary5: '#000056',
                secondary6: '#422B89',
                secondary7: '#5D42A4',
                secondary8: '#785ABF',
                secondary9: '#9473DB',
                secondary10: '#B08DF8',
                text: '#FFFFFF',
                text1: '#E2E2E2',
                text2: '#C6C6C6',
                text3: '#ABABAB',
                text4: '#919191',
                text5: '#777777',
                base: '#1E1E1E',
              },
              light: {
                primary: '#F524FC',
                secondary: '#25146F',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#FFCFFF',
                primary2: '#FFB0FF',
                primary3: '#FF91FF',
                primary4: '#FF71FF',
                primary5: '#FF4FFF',
                primary6: '#D600DF',
                primary7: '#B800C2',
                primary8: '#9A00A7',
                primary9: '#7C008C',
                primary10: '#5E0071',
                secondary1: '#B08DF8',
                secondary2: '#9473DB',
                secondary3: '#785ABF',
                secondary4: '#5D42A4',
                secondary5: '#422B89',
                secondary6: '#000056',
                secondary7: '#00003F',
                secondary8: '#00002A',
                secondary9: '#000019',
                secondary10: '#000000',
                text: '#FFFFFF',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
            dark: true,
          },
          state: {
            mainBackgroundImg:
              'https://wallpaperboat.com/wp-content/uploads/2021/09/27/78941/neon-08-920x518.jpg',
            backgroundImg:
              'https://wallpaperboat.com/wp-content/uploads/2021/09/27/78941/neon-08-920x518.jpg',
            backImg: true,
            backgroundBlur: 0,
            backTintOpacity: 0.8,
            selectedMediaBackground: false,
            tintColor: '#000011FF',
            panelOpacity: 'B3',
            menuOpacity: 'CC',
          },
        },
      },
      {
        name: 'vscode',
        value: {
          vuetify: {
            themes: {
              dark: {
                primary: '#007ACC',
                secondary: '#1E1E1E',
                accent: '#FF4081',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#000649',
                primary2: '#002061',
                primary3: '#00347B',
                primary4: '#004A95',
                primary5: '#0061B0',
                primary6: '#3F94E8',
                primary7: '#62AEFF',
                primary8: '#82C9FF',
                primary9: '#A1E5FF',
                primary10: '#C0FFFF',
                secondary1: '#000000',
                secondary2: '#000000',
                secondary3: '#000000',
                secondary4: '#000000',
                secondary5: '#050505',
                secondary6: '#333333',
                secondary7: '#4A4A4A',
                secondary8: '#616161',
                secondary9: '#7A7A7A',
                secondary10: '#949494',
                text: '#FFFFFF',
                text1: '#E2E2E2',
                text2: '#C6C6C6',
                text3: '#ABABAB',
                text4: '#919191',
                text5: '#777777',
                base: '#1E1E1E',
              },
              light: {
                primary: '#007ACC',
                secondary: '#1E1E1E',
                accent: '#82B1FF',
                error: '#FF5252',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                primary1: '#C0FFFF',
                primary2: '#A1E5FF',
                primary3: '#82C9FF',
                primary4: '#62AEFF',
                primary5: '#3F94E8',
                primary6: '#0061B0',
                primary7: '#004A95',
                primary8: '#00347B',
                primary9: '#002061',
                primary10: '#000649',
                secondary1: '#949494',
                secondary2: '#7A7A7A',
                secondary3: '#616161',
                secondary4: '#4A4A4A',
                secondary5: '#333333',
                secondary6: '#050505',
                secondary7: '#000000',
                secondary8: '#000000',
                secondary9: '#000000',
                secondary10: '#000000',
                text: '#FFFFFF',
                text1: '#FFFFFF',
                text2: '#FFFFFF',
                text3: '#FFFFFF',
                text4: '#FFFFFF',
                text5: '#FFFFFF',
                base: '#1E1E1E',
              },
            },
            dark: true,
          },
          state: {
            mainBackgroundImg:
              'https://i.postimg.cc/HnJP4bjD/gradient-linear-gray-1920x1080-c2-1e1e1e-1e1e1e-a-285-f-14.jpg',
            backgroundImg:
              'https://i.postimg.cc/HnJP4bjD/gradient-linear-gray-1920x1080-c2-1e1e1e-1e1e1e-a-285-f-14.jpg',
            backImg: true,
            backgroundBlur: 20,
            backTintOpacity: 0.6,
            selectedMediaBackground: true,
            tintColor: '#1F1F1FFF',
            panelOpacity: 'FF',
            menuOpacity: 'FF',
          },
        },
      },
    ],
  }),
  computed: {
    selectedTheme() {
      const obj = {}
      obj.vuetify = {}
      obj.vuetify.themes = _.cloneDeep(this.$vuetify.theme.themes)
      obj.vuetify.dark = _.cloneDeep(this.$vuetify.theme.dark)
      obj.state = _.cloneDeep(this.$store.state.Settings.Appearance)
      delete obj.state.gridCardWidth
      delete obj.state.horizontalCardWidth
      return this.themes.findIndex(theme => _.isEqual(theme.value, obj))
    },
    jsonTheme() {
      const obj = {}
      obj.vuetify = {}
      obj.vuetify.themes = _.cloneDeep(this.$vuetify.theme.themes)
      obj.vuetify.dark = _.cloneDeep(this.$vuetify.theme.dark)
      obj.state = _.cloneDeep(this.$store.state.Settings.Appearance)
      delete obj.state.gridCardWidth
      delete obj.state.horizontalCardWidth
      return obj
    },
  },
  methods: {
    changeTheme(theme) {
      this.$store.state.Settings.Appearance = {
        ...this.$store.state.Settings.Appearance,
        ...theme.value.state,
      }
      this.$vuetify.theme.dark = theme.value.vuetify.dark
      Object.keys(theme.value.vuetify.themes.dark).forEach(key => {
        Vue.set(this.$vuetify.theme.themes.dark, key, theme.value.vuetify.themes.dark[key])
      })
      Object.keys(theme.value.vuetify.themes.light).forEach(key => {
        Vue.set(this.$vuetify.theme.themes.light, key, theme.value.vuetify.themes.light[key])
      })
    },
  },
}
</script>

<style lang="scss" scoped>
::v-deep .v-input {
  max-width: 200px;
  min-width: 200px;
}
::v-deep .v-btn:hover {
  transform: scale(1.05);
  z-index: 2;
}
::v-deep .v-btn::before {
  content: none;
}
</style>
