name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint main package
        run: npm run packages:main:lint

      - name: Lint preload package
        run: npm run packages:preload:lint

      - name: Lint renderer package
        run: npm run packages:renderer:lint

    # - name: Build Electron
    #   run: npm run electron:build
